name: SkinCustomizer
version: '1.0-SNAPSHOT'
main: dev.jensderuiter.skincustomizer.CustomizerPlugin
api-version: '1.20'
authors: [ jensjeflensje ]
website: https://jensderuiter.dev
depend: [Citizens, SkinsRestorer]
commands:
  customizer:
